### ISSUE TITLE
Installation instructions and vignettes in README 

### ISSUE THREAD

**Issue by ivan-paleo** [NicolasStefaniak/easieR#11]
I would recommend to list the installation instructions directly in the README, or at least add a link to them. As it is, it is actually quite complicated to find the installation instructions.

I would also detail how to open the vignettes directly in the README too.

**Comment by NicolasStefaniak** [comment]
I have updated the readme, following your suggestion. 
For the vignette, I need to see how github can handle Rmarkdown files. 
I know it is possible but I have not find it yet. 
Thank you for the suggestion,
Best,
Nicolas

**Comment by ivan-paleo** [comment]
There are a few typos, but it looks good!
